FORMAT: 1A
HOST: http://auction.stc.com.sa/ 


# Auction REST API

TODO : Add auction intoduction.

## HTTP request headers

  * Content-Type - The format of the request body - only application/json is supported at this time
  * Accept-Language - The language that you want the descriptions returned in - not currently supported
  
## HTTP response codes

  * 200 - The request completed OK
  * 201 - The specified object was created sucessfully
  * 204 - The request completed OK (No Content)
  * 400 - The request was not understood
  * 403 - You do not have access to the requested object
  * 404 - The object that was requested doesn't exist
  * 405 - The resource exists, but the wrong method was used. 
  * 500 - There was an internal API error
  * 501 - You have used a method (GET/PUT/POST/DELETE/etc) not supported by this endpoint
  
## HTTP response headers

  * Content-Type - The format of the response body eg. application/json
  * Location - When an object has been created following a POST, it's location will be contained here

## Bids Collection [/v1/bids]

### Create a New Bids [POST]

You may create your own bid using this action. It takes a JSON
object containing a product id,user id and a amount of bid.

+ Request (application/json)

        {
            "user_id": 123,
            "product_id":1004,
            "bid_amount": 5000
        }

+ Response 201 (application/json)

    + Headers

            Location: /bids/1458

    + Body

            {
               "number_of_bids": 37,
               "bid_amount": 5000,
               "is_highest_bidder:"true"

            }
            
+ Response 500 (application/json)
    
    + Body

            {
                "error":  {
                "code": "AUC001",
                "error_title": "A title",
                "error_message": "A message" }
            }