FORMAT: 1A
HOST: http://auction.stc.com.sa/


# Auction REST API v1.0

The Auction API provides a list of API for developers to interact with Auction system.
 
## HTTP request headers

The following is a mandatory header tags, that must be sent with each request.
  * content-type - The format of the request body - only application/json is supported at this time
  * accept-language - The language that you want the descriptions returned in - eg. en/ar.
  * channel-Id - The identity of the caller - only predefined channels are allowed to consume the API.
  * client-Ip  - The ip address of client.
  * user-agent - The app version of the mobile application that tries to consume the API.
  * api-version - The API version of auction application - eg. v1, otherwise don't send this tag to get the latest version 
  * authorization - base64 encoded credentials.
  
## HTTP response codes

  * 200 - The request completed OK
  * 201 - The specified object was created sucessfully
  * 204 - The request completed OK (No Content)
  * 400 - The request was not understood
  * 403 - You do not have access to the requested object
  * 404 - The object that was requested doesn't exist
  * 405 - The resource exists, but the wrong method was used. 
  * 500 - There was an internal API error
  * 501 - You have used a method (GET/PUT/POST/DELETE/etc) not supported by this endpoint
  
## HTTP response headers

  * Content-Type - The format of the response body eg. application/json

## User Collection [/users]

### Add User [POST]
Add User

+ Request (application/json)
    
    + Body
        
            {
              "username": "user",
              "password": "password",
              "channelId": "1",
              "groups": [
                {
                "id": 1
                }
               ]
            }
            
+ Response 201 (application/json)
            
    + Body
        
            {
                "username": "user", 
                "channelId": "1"
            }

+ Response 400 (application/json)

    **Error Code:**
    - AUC008 : Auction Batchs overlap is not allowed.
    - AUC009 : Invalid Request body.
    
    + Attributes
        + errorCode (string) - Auction error code 
        + fieldErrors (string) -  fields that has errors.
    
    + Body
    
            {
                "errorCode": "VALIDATION_ERROR",
                "fieldErrors": [
                    {
                        "field": "channelId",
                        "message": "may not be null"
                    }
                ]
            }
                 
                 
## Categories Collection [/categories]     

### List all Categorires [GET]  

Return list of all Categorires

+ Request (application/json)

    + Headers

            Accept-Language: en
            
+ Response 200 (application/json)

        {
          "Categories": [
            {
              "id": 2,
              "name": "Diamond",
              "minimumIncrement": 200,
              "links": {
                "self": {
                  "href": "http://auction.stc.com.sa/category/2"
                }
              }
            },
            {
              "id": 1,
              "name": "Gold",
              "minimumIncrement": 200,
              "links": {
                "self": {
                  "href": "http://auction.stc.com.sa/category/1"
                }
              }
            }
          ]
        }

## Categories Detail [/categories/{id}]     

+ Parameters
    + id: `1` (number, required) - Id of a Category.
    
### Retrieve a Category [GET]  

Returns a single Category

+ Request (application/json)

    + Headers

            Accept-Language: en
            
+ Response 200 (application/json)

            {
               "id":2,
               "name": "Diamond",
               "minimumIncrement": 200,
               "depositAmount":1000,
               "isAutoBidAllowed" : "true",
               "isPurchaseAllowed" : "true",
               "purchasePrice":100000,
               "numberOfBidToStartAutoBid" : 25,
               "purchaseDisablePercentege" : 80
            }
            
+ Response 500 (application/json)


    + Attributes
        + errorCode (string) - Auction error code 
        + message (string) -  customer message returned by the auction API.
        
    + Body      
    
            {
                "errorCode": "AUC006",
                "message": "Element Not found."
            }
        

### Update a Category [PUT]

+ Request (application/json)

    + Headers

            Accept-Language: en
            
    + Body
            
            {   
               "arabicName": "ماسي",
               "englishName": "Diamond",
               "minimumIncrement": 200,
               "depositAmount":1000,
               "isAutoBidAllowed" : "true",
               "isPurchaseAllowed" : "true",
               "purchasePrice":100000,
               "numberOfBidToStartAutoBid" : 25,
               "purchaseDisablePercentege" : 80
            }

+ Response 204 (application/json)

+ Response 500 (application/json)

## Products Collection [/products{?page,size,sort,order,categoryId,msisdn}]

### Add Products [POST]
Add list of products

+ Request (application/json)
    + Body
            
            {
              "startDate": "2017-11-19T12:4:00.000",
              "auctionNumbers": [
                {
                  "categoryId": 31,
                  "number": "500008802"
                },
                {
                  "categoryId": 29,
                  "number": "500009020"
                },
                {
                  "categoryId": 26,
                  "number": "505555007"
                }
              ],
              "endDate": "2017-11-29T12:2:59.999",
              "batchId": "AUC1000057"
            }
+ Response 204


+ Response 500 (application/json)

    **Error Code:**
    - AUC008 : Auction Batchs overlap is not allowed.
    - AUC009 : Invalid Request body.
    
    + Attributes
        + errorCode (string) - Auction error code 
        + message (string) -  customer message returned by the auction API.
    
    + Body
    
            {
                "errorCode": "AUC008",
                "message": "Auction Batchs overlap is not allowed",
            }
                    
### List All Products [GET]

Return list of all products

+ Parameters
    + page      (number, optional)
      + Default: 0
    + size      (number, optional)
      + Default: 100
    + sort     (optional)
      + Default: `id`
      + Members
            + `price`
            + `numberOfBids`
            + `views` 
            + `id`
    + order     (optional)
      + Default: `ASC`
      + Members
            + `ASC`
            + `DESC`
    + categoryId (number, optional)
    + msisdn (number, optional)
    
+ Response 200 (application/json)
 
        {
          "products": [
            {
              "id": 1001,
              "msisdn": "533996655",
              "currentPrice": 8000,
              "productStatus": "sold",
              "category": {
                "id": 1,
                "name": "Gold",
                "minimumIncrement": 200,
                "links": {
                  "self": {
                    "href": "http://auction.stc.com.sa/category/1"
                  }
                }
              },
              "links": {
                "self": {
                  "href": "http://auction.stc.com.sa/products/1001"
                }
              }
            },
            {
              "id": 1002,
              "msisdn": "5399999999",
              "currentPrice": 8000,
              "productStatus": "new",
              "category": {
                "id": 2,
                "name": "Diamond",
                "minimumIncrement": 200,
                "links": {
                  "self": {
                    "href": "http://auction.stc.com.sa/category/2"
                  }
                }
              },
              "links": {
                "self": {
                  "href": "http://auction.stc.com.sa/products/1002"
                }
              }
            }
          ],
          "links": {
            "self": {
              "href": "http://auction.stc.com.sa/products?page=1&size=2"
            },
            "first": {
              "href": "http://auction.stc.com.sa/products?page=0&size=2"
            },
            "prev": {
              "href": "http://auction.stc.com.sa/products?page=0&size=2"
            },
            "next": {
              "href": "http://auction.stc.com.sa/products?page=2&size=2"
            },
            "last": {
              "href": "http://auction.stc.com.sa/products?page=49&size=2"
            }
          },
          "page": {
            "size": 2,
            "totalElements": 100,
            "totalPages": 50,
            "number": 1
          }
        }
  
 
## Products Detail [/products/{id}{?customerId}]     

### View a product detail [GET]

Return a single product detail resource.

+ Parameters

    + id: `1001` (number, required) - Id of a product.
    + customerId:`1` (optional) - send customerId if you looking for customer status. 
                                        
+ Response 200 (application/json)

    + Attributes  
        + id (string) - Id of a product.
        + msisdn (string) - auction number
        + currentPrice (string) - auction last price.
        + expiryDate  (string) - auction expiry date.
        + numberOfBids (number) - totale number of bids.
        + hasAutoBid  (string) - return if auto bid featuer enabled or disable
        + productStatus (enum[string]) - return list of product status
            + Members
                + `sold` 
                + `new`
        + customerBidStatus (enum[string]) -  return list of bid status belongs to a specific customer, return none if no customer sent in the request 
            + Members
                + `noBid`
                + `highestBidder`
                + `outbid` 
                + `none`
        + category  - 
            + id  (number) - Id of a product.
            + name (string) - name of a category
            + minimumIncrement (string)  - category minimum Increment
        + projection (enum[string]) -  possible values detail or summary. 
            + Members
                + `detail` - return all product detail fields. 
                + `summary` - return currentPrice, numberOfBids , hasAutoBid , productStatus , customerBidStatus fields.
    + Body
    
            {
              "id": 1001,
              "msisdn": "533996655",
              "currentPrice": 8000,
              "expiryDate": "12/13/2015 11:51:59.000000 AM",
              "numberOfBids": 15,
              "hasAutoBid": false,
              "productStatus": "sold",
              "customerBidStatus": "none",
              "category": {
                "id":2,
                "name": "Diamond",
                "minimumIncrement": 200
                "links": {
                  "self": {
                    "href": "http://auction.stc.com.sa/category/1"
                  }
                }
              }
            }

+ Response 500 (application/json)

    + Attributes
        + errorCode (string) - Auction error code 
        + message (string) - customer message returned by the auction API.
            
    + Body
            
                {
                    "errorCode": "AUC006",
                    "message": "Element Not found"
                }

       
## Search  [/search{?page,size,msisdn}]

### Search [GET]

Return a list of all matched msisdn

+ Parameters
    + page      (number, optional)
      + Default: 0
    + size      (number, optional)
      + Default: 10
    + msisdn (number, optional)
    
+ Response 200 (application/json)

    + Attributes  
        
        + msisdn (string) - The auction number

    + Body  
        
            {
              "products": [
                {
                  "msisdn": "50000655",
                  "links": {
                    "self": {
                      "href": "http://auction.stc.com.sa/products/1"
                    }
                  }
                },
                {
                  "msisdn": "533996655",
                  "links": {
                    "self": {
                      "href": "http://auction.stc.com.sa/products/2"
                    }
                  }
                }
              ],
              "links": {
                "self": {
                  "href": "http://auction.stc.com.sa/products?page=1&size=2"
                },
                "first": {
                  "href": "http://auction.stc.com.sa/products?page=0&size=2"
                },
                "prev": {
                  "href": "http://auction.stc.com.sa/products?page=0&size=2"
                },
                "next": {
                  "href": "http://auction.stc.com.sa/products?page=2&size=2"
                },
                "last": {
                  "href": "http://auction.stc.com.sa/products?page=49&size=2"
                }
              },
              "page": {
                "size": 2,
                "totalElements": 100,
                "totalPages": 50,
                "number": 1
              }
            }
            
## Bids Collection [/bids]

### Place a New Bids [POST]

You may create your own bid using this action. It takes a JSON
object containing a customer id and a amount of bid.


+ Request (application/json)


    + Headers

            Accept-Language: en
            
    + Body
            
            {
                "customer": {
                    "nationalId": 10999999, 
                    "email": "test@stc.com",
                    "firstName": "Waseem",
                    "lastName": "judeh",
                    "username": "wjudeh",
                    "contactNumber": 055555555
                }
                "bidAmount": 5000,
                "hasAutoBid": "true",
                "productId": 1
            }

+ Response 201 (application/json)

    + Attributes 
    
        + numberOfBids (number) - totale number of bids.
        + hasAutoBid  (string) - return weather of auto bid featuer enabled or disable
        + bidAmount (string) - return last bid amount.
        + customerBidStatus (enum[string]) -  return list of bid status belongs to a specific customer, return none if no customer sent in the request 
            + Members
                + `noBid`
                + `highestBidder`
                + `outbid` 
                + `none`
        
    + Body
    
            {
               "numberOfBids": 37,
               "bidAmount": 5000,
               "customerBidStatus": "highestBidder",
               "hasAutoBid":true
            }

+ Response 400 (application/json)
        
  **Error Code:**
    - AUC001 : customer doesn't pay deposit payment.
    - AUC002 : customer is blacklisted in auction.
    - AUC003 : customer is already highest bidder.
    - AUC004 : Auction is not active.
    - AUC005 : Bid is less than minimum bid.
    - AUC007 : wrong bid type
    
    + Attributes
        + errorCode (string) - Auction error code 
        + message (string) -  customer message returned by the auction API.
        
    + Body

                {
                    "errorCode": "AUC001",
                    "message": "To complete the bidding process on this number,you must pay a deposit payment",
                }
                
## Batchs Collection [/batches]

### List all Batches  [GET]

Return list of all Batches

+ Request (application/json)

    + Headers

            Accept-Language: en
            
+ Response 200 (application/json)

        {
          "batches": [
            {
              "id": "AUC0003",
              "endDate": "2017-05-24T14: 25: 10"
            },
            {
              "id": "AUC0004",
              "endDate": "2016-05-24T14: 25: 10"
            }
          ]
        }